version: '3.7'

services:
  apiserver:
    build: .
    environment:
      SEQ_URL: http://seq:5341
    ports:
      - "5000:8080"
    depends_on:
      - seq
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ./data/seq:/data
