version: '3.7'

services:
  apiserver:
    build: ./server
    environment:
      SEQ_URL: http://seq:5341
    ports:
      - "5000:8080"
    depends_on:
      - seq
      - rabbit
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ./data/seq:/data
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - ./data/mongo:/data/db